/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.cifpaviles.dam.actividad6_tema1_josemanuel;

import javax.swing.DefaultListModel;

/**
 *
 * @author josemmr
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private DefaultListModel<String> modeloLista;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        modeloLista=new DefaultListModel<>();
        listaTareas.setModel(modeloLista);
        
        // boton Añadir con lambda
        btnAniadir.addActionListener(e -> {
            String tarea = txtTarea.getText().trim();
            if (!tarea.isEmpty()) {
            modeloLista.addElement(tarea);
            txtTarea.setText("");
            labelEstado.setText("Tarea añadida: " + tarea);
            } else {
            labelEstado.setText("No puedes añadir una tarea vacía");
            }
        });

        // añadir tarea al pulsar Enter en JTextField
        txtTarea.addActionListener(e -> {
            String tarea = txtTarea.getText().trim();
            if (!tarea.isEmpty()) {
                modeloLista.addElement(tarea);
                txtTarea.setText("");
                labelEstado.setText("Tarea añadida: " + tarea);
            }
        });

        // boton borrar con clase interna anónima
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int index = listaTareas.getSelectedIndex();
                if (index != -1) {
                    String tarea = modeloLista.getElementAt(index);
                    modeloLista.remove(index);
                    labelEstado.setText("Tarea eliminada: " + tarea);
                } else {
                 labelEstado.setText("No hay tarea seleccionada");
                }
            }
        });

        // doble clic en la lista
        listaTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = listaTareas.locationToIndex(e.getPoint());
                    if (index != -1) {
                        String tarea = modeloLista.getElementAt(index);
                        javax.swing.JOptionPane.showMessageDialog(
                            null,
                            "Has hecho doble clic sobre la tarea: " + tarea
                        );
                    }
                }
            }
        });

        // KeyListener para cuando se pulsa la tecla SUPR
        listaTareas.addKeyListener(new KeyHandler());

        // menu “Salir”
        salir.addActionListener(e -> {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "¿Deseas salir del programa?",
                "Confirmación",
                javax.swing.JOptionPane.YES_NO_OPTION
            );
            if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        });

        // WindowListener para confirmar cierre
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int opcion = javax.swing.JOptionPane.showConfirmDialog(
                    null,
                    "¿Deseas salir del programa?",
                    "Confirmación",
                    javax.swing.JOptionPane.YES_NO_OPTION
                );
                if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTarea = new javax.swing.JTextField();
        btnAniadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        labelEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTareas = new javax.swing.JList<>();
        menuSalir = new javax.swing.JMenuBar();
        acciones = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTareaActionPerformed(evt);
            }
        });

        btnAniadir.setText("Añadir");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");

        labelEstado.setText("Mensaje de estado");

        jScrollPane1.setViewportView(listaTareas);

        acciones.setText("Acciones");

        salir.setText("Salir");
        acciones.add(salir);

        menuSalir.add(acciones);

        setJMenuBar(menuSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAniadir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar))
                            .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAniadir)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed

        String tarea = txtTarea.getText().trim();
        if (!tarea.isEmpty()) {
            modeloLista.addElement(tarea);   
            txtTarea.setText("");           
            labelEstado.setText("Tarea añadida: " + tarea);
        } else {
            labelEstado.setText("No puedes añadir una tarea vacía");
}

    }//GEN-LAST:event_btnAniadirActionPerformed

    private void txtTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acciones;
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JList<String> listaTareas;
    private javax.swing.JMenuBar menuSalir;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTextField txtTarea;
    // End of variables declaration//GEN-END:variables

class KeyHandler implements java.awt.event.KeyListener {
    @Override public void keyTyped(java.awt.event.KeyEvent e) {}
    @Override public void keyReleased(java.awt.event.KeyEvent e) {}
    @Override
    public void keyPressed(java.awt.event.KeyEvent e) {
        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE) {
            int index = listaTareas.getSelectedIndex();
            if (index != -1) {
                String tarea = modeloLista.getElementAt(index);
                modeloLista.remove(index);
                labelEstado.setText("Tarea eliminada con SUPR: " + tarea);
            }
        }
    }
}

}
